package interfaceGrafica;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


public class PainelConectar extends javax.swing.JDialog {

    /**
     * Creates new form PainelCadastro
     */
    public PainelConectar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jNome = new javax.swing.JTextField();
        jServidor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("Insira o seu nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 120, 20));

        jNome.setForeground(new java.awt.Color(0, 102, 51));
        getContentPane().add(jNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 220, 30));

        jServidor.setBackground(new java.awt.Color(204, 204, 204));
        jServidor.setForeground(new java.awt.Color(0, 102, 51));
        jServidor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jServidor.setText("venus.inf.ufsc.br");
        jServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jServidorActionPerformed(evt);
            }
        });
        getContentPane().add(jServidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 270, -1));

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 51));
        jButton1.setText("►");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 50, 30));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/painel.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!jNome.getText().equalsIgnoreCase("")){
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jServidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jServidorActionPerformed

    public String getTextField(){
        return jNome.getText();
    }
    
    public String getServidor(){
        return jServidor.getText();
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fundo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jNome;
    private javax.swing.JTextField jServidor;
    // End of variables declaration//GEN-END:variables
}
